version: '3'
services:
  db:
    image: postgres:9.6.3-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: "none"
  app:
    image: nicoleivanov/connect-lite:account
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7000:7000"
    networks:
      - webnet
networks:
  webnet:
